spring.application.name= ${SPRING_APP_NAME:Book_Management}
spring.datasource.url=jdbc:postgresql://localhost:5432/ryoka
spring.datasource.username=ryu
spring.datasource.password=ABDK

spring.security.user.name=${SECURITY_USERNAME:Deep}
spring.security.user.password=${SECURITY_PASSWORD:12345}
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss:SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15})-%msg%n}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always